toolImage: artcsp-docker.ara-artifactory.volvocars.biz/vcc/common-build-agent:0.12.0
version: 1
build:
  steps:
    - type: compose
      nodes:
        dev:
          image: artcsp-docker.ara-artifactory.volvocars.biz/vcc/common-build-dev:0.7.0
      commands:
        - cmd: npm install && npm run build
    - type: build
      name: vcc/common-build-agent
      file: docker/Dockerfile
  optimizers: null
